# Generated by Django 4.2.7 on 2024-02-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_title_m_alter_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
