# Generated by Django 4.2.7 on 2024-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='explain',
            field=models.CharField(max_length=300),
        ),
    ]
