# Generated by Django 4.2.7 on 2024-02-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title_m',
            field=models.CharField(max_length=10),
        ),
    ]
